name: GitHub Classroom Workflow

on:
  push:
    branches:
    - '*'    

env:
  DBPASS: 'Pa$$w0rd1234'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    # setup sql server service
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ env.DBPASS }}
        ports:
        - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P \"${SA_PASSWORD}\" -Q \"SELECT 1\" -b -o /dev/null"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 5
          --health-start-period 10s

    steps:
      - uses: actions/checkout@v2

      - name: check docker containers
        run: docker ps -a

      - name: check sql server running
        run: sqlcmd -S 127.0.0.1 -U SA -P 'Pa$$w0rd1234' -Q "SELECT NAME FROM sys.sysdatabases"

      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        id: autograder
      #   continue-on-error: true

      # # fail job if autograder returns failed
      # # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
      # # trigger fail either on !success or on failure depending on preference
      # - name: check autograder pass fail
      #   if: ${{ steps.autograder.outcome != 'success' }}
      #   # if: ${{ steps.autograder.outcome == 'failure' }}
      #   # if: ${{ failure }}
      #   run: exit 1

    outputs:
      grading-score: ${{ steps.autograder.outputs.Points }}